TARGETS = [
    ("plumber",      "Gallup, NM"),
    ("electrician",  "Tooele, UT"),
    ("auto repair",  "Hobbs, NM"),
    ("painter",      "Clovis, NM"),
    ("hair salon",   "Stillwater, OK"),
    ("plumber",      "Vernal, UT"),
    ("locksmith",    "Dodge City, KS"),
    ("electrician",  "Alamogordo, NM"),
    ("roofing",      "Liberal, KS"),
    ("auto body",    "Douglas, AZ"),
    ("plumber",      "Rawlins, WY"),
    ("handyman",     "Altus, OK"),
    ("electrician",  "Greenwood, MS"),
    ("pest control", "Lufkin, TX"),
    ("painter",      "Crowley, LA"),
    # roofing contractors across all non-Gallup locations
    ("roofing",      "Tooele, UT"),
    ("roofing",      "Hobbs, NM"),
    ("roofing",      "Clovis, NM"),
    ("roofing",      "Stillwater, OK"),
    ("roofing",      "Vernal, UT"),
    ("roofing",      "Dodge City, KS"),
    ("roofing",      "Alamogordo, NM"),
    ("roofing",      "Douglas, AZ"),
    ("roofing",      "Rawlins, WY"),
    ("roofing",      "Altus, OK"),
    ("roofing",      "Greenwood, MS"),
    ("roofing",      "Lufkin, TX"),
    ("roofing",      "Crowley, LA"),
]